from enum import Enum

class RiskCategory(str, Enum):
    AUTO_RENEWAL = "auto_renewal"
    TERMINATION_UNILATERAL = "termination_unilateral"
    LOCK_IN = "lock_in"
    NOTICE_PERIOD_ASYMMETRY = "notice_period_asymmetry"
    DEPOSIT_FORFEITURE = "deposit_forfeiture"
    PENALTY = "penalty"
    LATE_FEES = "late_fees"
    UNILATERAL_AMENDMENT = "unilateral_amendment"
    INDEMNITY = "indemnity"
    LIMITATION_OF_LIABILITY = "limitation_of_liability"
    NON_COMPETE = "non_compete"
    IP_ASSIGNMENT = "ip_assignment"
    CONFIDENTIALITY_SCOPE = "confidentiality_scope"
    DATA_SHARING = "data_sharing"
    DISPUTE_RESOLUTION = "dispute_resolution"
    GOVERNING_LAW = "governing_law"
    ASSIGNMENT = "assignment"
    FORCE_MAJEURE = "force_majeure"
    PAYMENT_TERMS = "payment_terms"
    HIDDEN_FEES = "hidden_fees"
    SERVICE_BOND = "service_bond"
    EXCLUSIONS = "exclusions"
    REGISTRATION = "registration"
    WAIVER_OF_RIGHTS = "waiver_of_rights"
    ENTIRE_AGREEMENT = "entire_agreement"
